# Generated by Django 5.2.14 on 2026-05-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("A", "Section A — MCQ"),
                            ("B", "Section B — Very Short Answer"),
                            ("C", "Section C — Short Answer"),
                            ("D", "Section D — Long Answer"),
                            ("E", "Section E — Case-based"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("VSA", "Very Short Answer"),
                            ("SA", "Short Answer"),
                            ("LA", "Long Answer"),
                            ("CASE", "Case-based"),
                        ],
                        max_length=4,
                    ),
                ),
                ("marks", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("options", models.JSONField(blank=True, default=list)),
                ("answer", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="accounts.school",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "id"],
            },
        ),
    ]
