# Generated by Django 5.2.15 on 2026-06-04 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("bank", "0012_question_answer_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("previous_year_paper", "Previous-year paper"),
                    ("sample_paper", "Sample paper"),
                    ("question_bank", "Question bank"),
                ],
                default="previous_year_paper",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="ingestion_uploads/")),
                ("source_file_name", models.CharField(blank=True, max_length=160)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("previous_year_paper", "Previous-year paper"),
                            ("sample_paper", "Sample paper"),
                            ("question_bank", "Question bank"),
                        ],
                        default="previous_year_paper",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_jobs",
                        to="accounts.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
