# Generated by Django 5.2.15 on 2026-06-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0013_alter_question_source_type_ingestionjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="review_flags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
