# Generated by Django 5.2.15 on 2026-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0014_question_review_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="thread_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
