# Generated by issue 191 implementation.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0017_generationbatch_generatedquestioncandidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationbatch",
            name="chapter_map_node_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
