# Generated by pi for issue 176

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0017_generationbatch_generatedquestioncandidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationbatch",
            name="chapter_map_node_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="generatedquestioncandidate",
            name="grounding_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
