# Generated by coding agent for issue 193

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0018_grounded_generation_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedquestioncandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready_for_review", "Ready for review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="ready_for_review",
                max_length=24,
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="generatedquestioncandidate",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
