# Generated by Django 5.2.15 on 2026-06-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0019_generatedquestioncandidate_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationbatch",
            name="discarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generationbatch",
            name="thread_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="generatedquestioncandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready_for_review", "Ready for review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("discarded", "Discarded"),
                ],
                db_index=True,
                default="ready_for_review",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="generationbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("generating_questions", "Generating Questions"),
                    ("validating", "Validating"),
                    ("ready_for_review", "Ready for review"),
                    ("accepted", "Accepted"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                    ("discarded", "Discarded"),
                ],
                db_index=True,
                default="queued",
                max_length=24,
            ),
        ),
    ]
