# Generated by Django 5.2.15 on 2026-06-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0021_reflag_enumeration_only_stems"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="pages_done",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="total_pages",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="ingestion_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="bank.ingestionjob",
            ),
        ),
    ]
