# Generated by Django 5.2.14 on 2026-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_consolidate_paper_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='document',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=10),
        ),
    ]
