# Generated by Django 5.2.15 on 2026-06-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0009_create_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="revision",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
