"""Prompt text for native-PDF Question extraction."""

from __future__ import annotations


def page_prompt() -> str:
    """Build the per-page extraction prompt (one PDF page in, English-only).

    The extractor feeds the model one page at a time, so the model reads a single
    page deeply instead of skimming the whole paper. Section is NOT requested
    verbatim — the coordinator derives it from each question's marks
    (``MARKS_TO_SECTION``).
    """
    return (
        "You are extracting questions from ONE PAGE of a CBSE Class 10 Science "
        "board paper into a question bank. The input is a single page image.\n\n"
        "Extract EVERY question that appears on this page. Include a question even "
        "if it looks partial (continued from the previous page or running onto the "
        "next) — copy whatever English text is on this page.\n\n"
        "Ignore anything that is not itself a question: the cover page, general "
        "instructions, the marking scheme, and any shared instruction or "
        "'Directions' block that introduces a group of questions (for example an "
        "assertion-reason answer-code key, 'For question numbers X and Y …', or "
        "'Read the following passage …'). Such a block is never a question on its "
        "own — do not emit it as a question, and never copy it into a question's "
        "rawText or stem.\n\n"
        "ENGLISH ONLY: these papers are bilingual. A page is usually entirely in "
        "one language — either Hindi (Devanagari) or English. If THIS page is in "
        "Hindi, return an empty list. If it is English, extract its questions. "
        "Never translate Hindi; emit no Devanagari characters.\n\n"
        "Copy each question VERBATIM from the English text — never paraphrase, "
        "correct, complete, or summarise it.\n\n"
        "ONE ENTRY PER PRINTED QUESTION OR OR-ALTERNATIVE: all sub-parts "
        "(i)/(ii)/(a)/(b) that belong to one answer stay inside that entry "
        "(content.subparts). If a question has an 'OR' alternative / internal "
        "choice, emit EACH alternative as its own separate question entry with "
        "the normal CBSE qtype implied by its marks.\n\n"
        "SYMBOLS: emit scientific symbols and units as LaTeX — an inline "
        "{type:'equation', latex:'...'} item, or the item's latex field (e.g. "
        "\\Omega for ohm, \\rightarrow, ^\\circ C). Never paste raw Unicode glyphs "
        "that may be garbled in the source scan.\n\n"
        "STRUCTURE:\n"
        "  - assertion_reason: put the Assertion sentence in content.assertion and "
        "the Reason sentence in content.reason; the fixed (A)–(D) 'Both A and R …' "
        "codes are the options. The shared Directions block is not the stem.\n"
        "  - mcq/assertion_reason: ALSO mirror the choices into content.options as "
        "labelled entries ([{label, content:[...]}]) — content.options is the "
        "source the renderer reads; never leave it empty for an objective question.\n"
        "Per question return:\n"
        "  section — the section letter (A–E) if a 'SECTION X' header is visible "
        "on this page, else your best guess; the importer re-derives it from marks.\n"
        "  qtype — one of: mcq, assertion_reason, very_short_answer, short_answer, "
        "long_answer, case_based. Do not emit internal_choice as a qtype.\n"
        "  marks — the integer mark value printed for the question (the digit at "
        "the right margin). This is important: the section is derived from it.\n"
        "  rawText — the stem copied verbatim, WITHOUT any visible marks "
        "(no '[1]', '(2 marks)', trailing mark digits) and WITHOUT option labels.\n"
        "  options — for mcq/assertion_reason: [{label, text}] verbatim; else [].\n"
        "  content — keyed by region, include only the regions the type uses:\n"
        "    stem / assertion / reason / passage: arrays of {type, text, latex?} "
        "where type is 'paragraph', 'equation', or 'image_placeholder'.\n"
        "    options / subparts: [{label, marks?, content:[item, ...]}].\n"
        "  chapter_slug — pick EXACTLY ONE slug from the allowed list the schema "
        "enumerates, or null if unsure. Never invent or reformat a slug.\n"
        "  cognitive_level — one of R, U, Ap, An.\n"
        "  topic_names — short topic strings within the chapter; [] if none.\n"
        "  primary_form — one of none, diagram_based, table_based.\n"
        "  figures — bounding boxes of any diagrams the question depends on, for "
        "deterministic cropping. [] if none. Each: {page, bbox, region, label?, "
        "caption?}. Set page to 1 (this is a single page); bbox is "
        "[x0, y0, x1, y1] normalized to [0, 1] with the page top-left as origin; "
        "region is the content region the figure belongs to (stem / assertion / "
        "reason / passage / options / subparts); label names the option/subpart "
        "for options/subparts.\n\n"
        "If a question depends on a figure or diagram, put a single "
        "{type:'image_placeholder', text:'<short description>'} item in the region "
        "where the figure appears AND add a matching entry to figures (same region "
        "and, for an option/subpart, the same label). The crop is made from the "
        "box; the placeholder is the anchor. Never invent pixels, options, or "
        "subparts."
    )
